/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Airdropper__factory } from "./Airdropper__factory";
export { ERC20Mock__factory } from "./ERC20Mock__factory";
